# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 9, 1, 2, 51, 28, 377854, tzinfo=utc)),
        ),
    ]
